### ISSUE TITLE
json-logic-java throws exceptions when the rule contains a forward slash(/)

### ISSUE THREAD

**Issue by bvarghese1** [jamsesso/json-logic-java#3]
Rule:
```{"in" : [{"var": "file_type"}, ["application/pdf","txt"]]}```
Data:
```{"file_type": "application/pdf"}```

Exception thrown:
```
io.github.jamsesso.jsonlogic.ast.JsonLogicParseException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line X column YY path $.in[1][1]
	at io.github.jamsesso.jsonlogic.ast.JsonLogicParser.parse(JsonLogicParser.java:21)
	at io.github.jamsesso.jsonlogic.JsonLogic.apply(JsonLogic.java:83)
```

**Comment by jamsesso** [comment]
I'm not able to reproduce this. Here is the unit test I wrote:

```java
  @Test
  public void testDataIn() throws JsonLogicException {
    Map data = Collections.singletonMap("file_type", "application/pdf");
    assertEquals(true, jsonLogic.apply("{\"in\" : [{\"var\": \"file_type\"}, [\"application/pdf\",\"txt\"]]}", data));
  }
```

**Comment by bvarghese1** [comment]
@jamsesso Thanks a lot for verifying! It was a bug at my end where I was not converting my rule to a valid string. I fixed my bug and it works as expected.
